#This file is use to validate our data
Filename: "Visadataset.csv"

NumberofColumn: 11 #After dropping case id column

ColumnNames :
  continent: category
  education_of_employee: category
  has_job_experience: category
  requires_job_training: category
  no_of_employees: int
  yr_of_estab: int
  region_of_employment: category
  prevailing_wage: float
  unit_of_wage: category
  full_time_position: category
  case_status: category

Numerical_col: 
 - prevailing_wage

Ordinal_columns:
 - has_job_experience
 - requires_job_training
 - full_time_position
 - education_of_employee

Onehot_columns:
 - continent
 - unit of wage
 - region_of_employment

Transformation_of_columns:
 - company_age
 - no_of_employees

Target_column:
 - case_status